version: 0.2

phases:
  install:
    runtime-versions:
      php: 8.1
    commands:
      - echo "[Install] nothing to install"
  build:
    commands:
      - echo "[Build] nothing to compile"

artifacts:
  files:
    - '**/*'          # include everything
  discard-paths: no   # <‑‑ KEEP PATHS so scripts/ stays scripts/

